version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: plataforma_r3_main_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: yoga-com-kaka
      POSTGRES_USER: plataforma
      POSTGRES_PASSWORD: senhaplataforma
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
